#!/bin/bash
source /home/tango/.sh.sh
source /etc/tangorc
source /home/tango/.env

# echo "$MYTEST_PREFIX"
echo "$PYTHONPATH"
echo "$PREFIX"

pixi add numpy pytango
# export OLD_PYTHONPATH="$PYTHONPATH"
# export PYTHONPATH="/path/to/your/custom/src:$PYTHONPATH"

# $MYTEST_PREFIX/TestServer $*
python /home/tango/bin/TestServer $*
